# -*- coding: utf-8 -*-
"""meta_labeling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15x18CPgAyOzvyAvaMx3D47HO16T-DJ7p
"""

def BPM(n): #총 10개의 label
    n = (n - 560)//4
    if n == 10:
        n = 9
    return n

def KEY(n): #총 5개의 label
    n = (n - 601)//5
    return n

def TIMESIGNATURE(n):#총 4개
    return n-626

def PITCHRANGE(n): #총 8개
    return n - 630

def NUMBEROFMEASURE(n): #총 3개
    return n-638


def INSTRUMENT(n): #총9개 
    return n - 641

def GENRE(n):
    return n-650

def MINVELOCITY(n):
    return n-653

def MAXVELOCITY(n):
    return n-653

def TRACKROLE(n):
    return n-719

def RHYTHM(n):
    return n-726
meta_list = [BPM,KEY,TIMESIGNATURE,PITCHRANGE,NUMBEROFMEASURE,
             INSTRUMENT,GENRE,MINVELOCITY,MAXVELOCITY,TRACKROLE,
             RHYTHM]